### PR TITLE
desidiff Module import fix

### PR DESCRIPTION
**Pull request by davidlmoutard**
changed the automatic file import- previously called module directory using '..', but the timedomain directory which houses desidiff is 2 directories above, so I changed it to '../../'

### CODE REVIEW

**Comment by AlexGKim** [comment]
Why are there changes around line 103?

**Comment by davidlmoutard** [comment]
> Why are there changes around line 103?

I believe that's where you said to change it since tid is an array- I put in your suggested for loop to iterate over all possible IDs in array.

**Comment by AlexGKim** [comment]
OK, you should then be explaining this in the pull request.

**Review by AlexGKim — APPROVED** [review]
Tested and works

**Pull request closed without merging**
